import type { Track } from "@/components/gosling";

const GWASURL = "https://higlass.genohub.org/api/v1/tileset_info/?d=gwas-hg38";

export const gwasTrack: Track = {
  alignment: "overlay",
  title: "GWAS Catalog",
  data: {
    url: GWASURL,
    type: "beddb",
    genomicFields: [
      { index: 1, name: "start" },
      { index: 2, name: "end" },
    ],
    valueFields: [
      { index: 6, name: "variant_vcf", type: "nominal" },
      { index: 7, name: "DATE ADDED TO CATALOG", type: "nominal" },
      { index: 8, name: "pubmedid", type: "nominal" },
      { index: 9, name: "FIRST AUTHOR", type: "nominal" },
      { index: 10, name: "date", type: "nominal" },
      { index: 11, name: "journal", type: "nominal" },
      { index: 12, name: "link", type: "nominal" },
      { index: 13, name: "study", type: "nominal" },
      { index: 14, name: "DISEASE/TRAIT", type: "nominal" },
      { index: 15, name: "INITIAL SAMPLE SIZE", type: "nominal" },
      { index: 16, name: "REPLICATION SAMPLE SIZE", type: "nominal" },
      { index: 17, name: "region", type: "nominal" },
      { index: 18, name: "REPORTED GENE(S)", type: "nominal" },
      { index: 19, name: "mapped_gene", type: "nominal" },
      { index: 20, name: "upstream_gene_id", type: "nominal" },
      { index: 21, name: "downstream_gene_id", type: "nominal" },
      { index: 22, name: "snp_gene_ids", type: "nominal" },
      { index: 23, name: "upstream_gene_distance", type: "nominal" },
      { index: 24, name: "downstream_gene_distance", type: "nominal" },
      { index: 25, name: "STRONGEST SNP-RISK ALLELE", type: "nominal" },
      { index: 26, name: "snps", type: "nominal" },
      { index: 27, name: "merged", type: "nominal" },
      { index: 28, name: "snp_id_current", type: "nominal" },
      { index: 29, name: "context", type: "nominal" },
      { index: 30, name: "intergenic", type: "nominal" },
      { index: 31, name: "RISK ALLELE FREQUENCY", type: "nominal" },
      { index: 32, name: "P-VALUE", type: "quantitative" },
      { index: 33, name: "pvalue_mlog", type: "nominal" },
      { index: 34, name: "P-VALUE (TEXT)", type: "nominal" },
      { index: 35, name: "OR or BETA", type: "nominal" },
      { index: 36, name: "95% CI (TEXT)", type: "nominal" },
      { index: 37, name: "PLATFORM [SNPS PASSING QC]", type: "nominal" },
      { index: 38, name: "cnv", type: "nominal" },
    ],
  },
  tracks: [
    {
      mark: "point",
      stroke: { value: "red" },
      strokeWidth: { value: 0.8 },
      opacity: { value: 0.7 },
      x: { field: "start", type: "genomic", linkingId: "link1" },
      y: {
        field: "P-VALUE",
        type: "quantitative",
        axis: "right",
      },
      row: {
        field: "context",
        type: "nominal",
        legend: true,
      },
      tooltip: [
        { field: "variant_vcf", type: "nominal", alt: "Variant VCF" },
        { field: "P-VALUE", type: "nominal", title: "P-Value" },
        {
          field: "RISK ALLELE FREQUENCY",
          type: "nominal",
          title: "Risk Allele Freq.",
        },
        { field: "DISEASE/TRAIT", type: "nominal", title: "Disease Trait" },
        { field: "study", type: "nominal", title: "Study" },
      ],
    },
  ],
  width: 800,
  height: 600,
};
