INSERT INTO production.variants_hg19 (
  variant_vcf, aloft_score, aloft_alof_description, aloft_alof_score,
  protein_variant, am_pathogenicity, am_class,
  qual, mutation_rate_filter, pn, mr, ar, mg, mc,
  clnsig, clnsigincl, clndn, clndnincl, clnrevstat, origin, clndisdb, clndisdbincl, geneinfo,
  gencode_category, gencode_info, gencode_exonic_category, gencode_exonic_info,
  apc_proximity_to_tss_tes_scaled_phred_score, mutation_density_apc_scaled_phred_score,
  gc, cpg, min_dist_tss, min_dist_tse, sift_cat, sift_val, polyphen_cat, polyphen_val,
  priphcons, mamphcons, verphcons, priphylop, mamphylop, verphylop, bstatistic,
  chmm_tssa, chmm_tssa_flnk, chmm_tx_flnk, chmm_tx, chmm_txwk, chmm_en_hg, chmm_en_h,
  chmm_znfrpts, chmm_het, chmm_tss_biv, chmm_biv_flnk, chmm_en_hbiv, chmm_reprpc,
  chmm_reprpc_wk, chmm_quies, gerp_n, gerp_s, ench3k27ac, ench3k4me1, ench3k4me3,
  grantham, freq100bp, rare100bp, sngl100bp, freq1000bp, rare1000bp, sngl1000bp,
  freq10000bp, rare10000bp, sngl10000bp, cadd_rawscore, cadd_phred, rsid,
  apc_conservation_v2, apc_epigenetics,
  sift_score, sift_pred, polyphen2_hdiv_score, polyphen2_hdiv_pred,
  polyphen2_hvar_score, polyphen2_hvar_pred, lrt_score, lrt_pred,
  mutationtaster_score, mutationtaster_pred, mutationassessor_score, mutationassessor_pred,
  fathmm_score, fathmm_pred, radialsvm_score, radialsvm_pred, lr_score, lr_pred, vest3_score,
  tg_all, tg_afr, tg_amr, tg_eas, tg_eur, tg_sas,
  apc_protein_function_v3, apc_transcription_factor,
  refseq_exonic_category, refseq_exonic_info, ucsc_exonic_category, ucsc_exonic_info
)
SELECT
  variant_vcf, aloft_score, aloft_alof_description, aloft_alof_score,
  alphamissense_protein_variant AS protein_variant,
  alphamissense_am_pathogenicity AS am_pathogenicity,
  alphamissense_am_class AS am_class,
  mutation_rate_qual AS qual, mutation_rate_filter AS mutation_rate_filter,
  mutation_rate_pn AS pn, mutation_rate_mr AS mr, mutation_rate_ar AS ar,
  mutation_rate_mg AS mg, mutation_rate_mc AS mc,
  clinvar_clnsig AS clnsig, clinvar_clnsigincl AS clnsigincl,
  clinvar_clndn AS clndn, clinvar_clndnincl AS clndnincl,
  clinvar_clnrevstat AS clnrevstat, clinvar_origin AS origin,
  clinvar_clndisdb AS clndisdb, clinvar_clndisdbincl AS clndisdbincl,
  clinvar_geneinfo AS geneinfo,
  genecode_comprehensive_genecode_comprehensive_category AS gencode_category,
  genecode_comprehensive_genecode_comprehensive_info AS gencode_info,
  genecode_comprehensive_exonic_genecode_comprehensive_exonic_category AS gencode_exonic_category,
  genecode_comprehensive_exonic_genecode_comprehensive_exonic_info AS gencode_exonic_info,
  apc_proximity_to_tss_tes_scaled_phred_score, mutation_density_apc_scaled_phred_score,
  gc, cpg, min_dist_tss, min_dist_tse, sift_cat, sift_val, polyphen_cat, polyphen_val,
  priphcons, mamphcons, verphcons, priphylop, mamphylop, verphylop, bstatistic,
  toFloat32OrNull(chmm_tssa) AS chmm_tssa,
  toFloat32OrNull(chmm_tssa_flnk) AS chmm_tssa_flnk,
  toFloat32OrNull(chmm_tx_flnk) AS chmm_tx_flnk,
  toFloat32OrNull(chmm_tx) AS chmm_tx,
  toFloat32OrNull(chmm_txwk) AS chmm_txwk,
  toFloat32OrNull(chmm_en_hg) AS chmm_en_hg,
  toFloat32OrNull(chmm_en_h) AS chmm_en_h,
  toFloat32OrNull(chmm_znfrpts) AS chmm_znfrpts,
  toFloat32OrNull(chmm_het) AS chmm_het,
  toFloat32OrNull(chmm_tss_biv) AS chmm_tss_biv,
  toFloat32OrNull(chmm_biv_flnk) AS chmm_biv_flnk,
  toFloat32OrNull(chmm_en_hbiv) AS chmm_en_hbiv,
  toFloat32OrNull(chmm_reprpc) AS chmm_reprpc,
  toFloat32OrNull(chmm_reprpc_wk) AS chmm_reprpc_wk,
  toFloat32OrNull(chmm_quies) AS chmm_quies,
  gerp_n, gerp_s,
  toFloat32OrNull(ench3k27ac) AS ench3k27ac,
  toFloat32OrNull(ench3k4me1) AS ench3k4me1,
  toFloat32OrNull(ench3k4me3) AS ench3k4me3,
  grantham,
  freq100bp, rare100bp, sngl100bp,
  freq1000bp, rare1000bp, sngl1000bp,
  freq10000bp, rare10000bp, sngl10000bp,
  cadd_rawscore, cadd_phred, rsid,
  apc_conservation_v2, apc_epigenetics,
  sift_score, sift_pred,
  polyphen2_hdiv_score, polyphen2_hdiv_pred,
  polyphen2_hvar_score, polyphen2_hvar_pred,
  lrt_score, lrt_pred,
  mutationtaster_score, mutationtaster_pred,
  mutationassessor_score, mutationassessor_pred,
  fathmm_score, fathmm_pred,
  radialsvm_score, radialsvm_pred,
  lr_score, lr_pred, vest3_score,
  tg_all, tg_afr, tg_amr, tg_eas, tg_eur, tg_sas,
  apc_protein_function_v3, apc_transcription_factor,
  refseq_exonic_category, refseq_exonic_info,
  ucsc_exonic_category, ucsc_exonic_info
FROM s3(
  'https://minio-s3-favor-4ee4be.apps.shift.nerc.mghpcc.org/hg19/partitioned_by_chr/chr={15,16,17,18,19,20,21,22}/*.parquet',
  'Parquet'
)
SETTINGS
  s3_max_single_read_retries = 10,
  s3_max_redirects = 5,
  max_threads = 8;